obj-$(CONFIG_HELLO)				+= hello/
obj-$(CONFIG_I2C_TEST)			+= i2c/
obj-$(CONFIG_GPIO_TEST)			+= gpio/
obj-$(CONFIG_GPIO_CTRL_TEST)	+= gpio_ctrl/
obj-$(CONFIG_INPUT_TEST)		+= input/
obj-$(CONFIG_TIMER_TEST)		+= timer/
obj-$(CONFIG_TIMER_LIST_TEST)	+= timer_list/

