    ...
    ...
    ...

static atomic_t xxx_available = ATOMIC_INIT(1);

static int xxx_open(struct inode *inode, struct file *filp)
{
    ...
    if (!atomic_dec_and_test(&xxx_available)) {
        atomic_inc(&xxx_available);
        return -EBUSY;
    }
    ...
    return 0;
}

static int xxx_release(struct inode *inode, struct file *filp)
{
    atomic_inc(&xxx_available);
    return 0;
}

    ...
    ...
    ...
